import { useState } from 'react'
import { FileText, Download, Eye, Search, Filter, Calendar, X } from 'lucide-react'
import { employees, salaryData, getNetSalary } from '../data/mockData'
import toast from 'react-hot-toast'

const statusBadgeClass = { Sent: 'badge-success', Generated: 'badge-purple', Pending: 'badge-warning' }

const SlipModal = ({ slip, emp, onClose }) => {
  if (!slip || !emp) return null
  const net = getNetSalary(slip)
  return (
    <div
      style={{
        position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.75)',
        backdropFilter: 'blur(6px)', zIndex: 100,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        padding: '20px',
      }}
      onClick={onClose}
    >
      <div
        style={{
          background: 'var(--bg-card)', border: '1px solid var(--border-bright)',
          borderRadius: '20px', width: '520px', maxWidth: '100%',
          animation: 'fadeInUp 0.25s ease',
        }}
        onClick={e => e.stopPropagation()}
      >
        {/* Slip Header */}
        <div style={{
          background: 'linear-gradient(135deg, #7c3aed, #4f46e5)',
          borderRadius: '18px 18px 0 0', padding: '28px 28px 24px',
          position: 'relative',
        }}>
          <button onClick={onClose} style={{
            position: 'absolute', top: '16px', right: '16px',
            background: 'rgba(255,255,255,0.15)', border: 'none', borderRadius: '8px',
            width: '32px', height: '32px', cursor: 'pointer', color: '#fff',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}><X size={16} /></button>
          <div style={{ fontFamily: 'Space Grotesk, sans-serif', fontWeight: 800, fontSize: '1.1rem', color: '#fff', marginBottom: '4px' }}>
            SALARY SLIP
          </div>
          <div style={{ fontSize: '0.8rem', color: 'rgba(255,255,255,0.7)' }}>
            {slip.month} {slip.year} • Generated by SalaryFlow
          </div>
          <div style={{ marginTop: '16px', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end' }}>
            <div>
              <div style={{ fontFamily: 'Space Grotesk, sans-serif', fontSize: '1.5rem', fontWeight: 800, color: '#fff' }}>{emp.name}</div>
              <div style={{ fontSize: '0.82rem', color: 'rgba(255,255,255,0.75)', marginTop: '2px' }}>
                {emp.designation} • {emp.department}
              </div>
              <div style={{ fontSize: '0.75rem', color: 'rgba(255,255,255,0.55)', marginTop: '2px' }}>
                {emp.id} • {emp.email}
              </div>
            </div>
            <div style={{ textAlign: 'right' }}>
              <div style={{ fontSize: '0.72rem', color: 'rgba(255,255,255,0.6)' }}>NET SALARY</div>
              <div style={{ fontFamily: 'Space Grotesk, sans-serif', fontSize: '1.8rem', fontWeight: 800, color: '#fff' }}>
                ₹{net.toLocaleString('en-IN')}
              </div>
            </div>
          </div>
        </div>

        {/* Breakdown */}
        <div style={{ padding: '24px 28px' }}>
          <div style={{ marginBottom: '16px' }}>
            <div style={{ fontSize: '0.72rem', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '10px' }}>
              Earnings
            </div>
            {[
              { label: 'Basic Salary', value: slip.baseSalary },
              { label: 'HRA',          value: slip.hra        },
              { label: 'Allowances',   value: slip.allowances },
            ].map(r => (
              <div key={r.label} style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px solid var(--border)' }}>
                <span style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>{r.label}</span>
                <span style={{ fontSize: '0.85rem', fontWeight: 600, color: '#34d399' }}>+₹{r.value.toLocaleString('en-IN')}</span>
              </div>
            ))}
          </div>

          <div style={{ marginBottom: '16px' }}>
            <div style={{ fontSize: '0.72rem', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '10px' }}>
              Deductions
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px solid var(--border)' }}>
              <span style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>Total Deductions</span>
              <span style={{ fontSize: '0.85rem', fontWeight: 600, color: '#f87171' }}>-₹{slip.deductions.toLocaleString('en-IN')}</span>
            </div>
          </div>

          <div style={{
            display: 'flex', justifyContent: 'space-between', alignItems: 'center',
            padding: '14px 16px',
            background: 'rgba(124,58,237,0.1)', border: '1px solid rgba(124,58,237,0.2)',
            borderRadius: '10px',
          }}>
            <span style={{ fontFamily: 'Space Grotesk, sans-serif', fontWeight: 700 }}>Net Salary</span>
            <span style={{ fontFamily: 'Space Grotesk, sans-serif', fontSize: '1.15rem', fontWeight: 800, color: '#a78bfa' }}>
              ₹{net.toLocaleString('en-IN')}
            </span>
          </div>

          <div style={{ display: 'flex', gap: '10px', marginTop: '20px' }}>
            <button className="btn-secondary" style={{ flex: 1 }} onClick={() => toast('PDF download — connect backend!')}>
              <Download size={14} /> Download PDF
            </button>
            <button className="btn-primary" style={{ flex: 1 }} onClick={() => { toast.success('Sent slip via email!'); onClose() }}>
              Send via Email
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

export default function SalarySlips() {
  const [search, setSearch]   = useState('')
  const [status, setStatus]   = useState('All')
  const [selected, setSelected] = useState(null)

  const enriched = salaryData.map(s => ({
    ...s,
    employee: employees.find(e => e.id === s.employeeId),
    net: getNetSalary(s),
  }))

  const filtered = enriched.filter(r => {
    const emp = r.employee
    const matchSearch = emp?.name.toLowerCase().includes(search.toLowerCase()) ||
      r.employeeId.toLowerCase().includes(search.toLowerCase())
    const matchStatus = status === 'All' || r.status === status
    return matchSearch && matchStatus
  })

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>

      {selected && (
        <SlipModal
          slip={selected}
          emp={selected.employee}
          onClose={() => setSelected(null)}
        />
      )}

      {/* Toolbar */}
      <div style={{ display: 'flex', gap: '12px', alignItems: 'center', flexWrap: 'wrap' }}>
        <div style={{
          display: 'flex', alignItems: 'center', gap: '8px', flex: 1, minWidth: '200px',
          background: 'var(--bg-card)', border: '1px solid var(--border-bright)',
          borderRadius: '10px', padding: '9px 14px',
        }}>
          <Search size={15} color="var(--text-muted)" />
          <input
            type="text"
            placeholder="Search by employee name or ID…"
            value={search}
            onChange={e => setSearch(e.target.value)}
            style={{ background: 'transparent', border: 'none', outline: 'none', color: 'var(--text-primary)', fontSize: '0.875rem', width: '100%' }}
          />
        </div>

        <div style={{ display: 'flex', gap: '6px' }}>
          <Filter size={14} color="var(--text-muted)" style={{ alignSelf: 'center' }} />
          {['All', 'Sent', 'Generated', 'Pending'].map(s => (
            <button key={s}
              onClick={() => setStatus(s)}
              style={{
                padding: '7px 14px', borderRadius: '8px', fontSize: '0.78rem',
                fontWeight: status === s ? 700 : 500, cursor: 'pointer',
                background: status === s ? 'rgba(124,58,237,0.2)' : 'var(--bg-card)',
                color: status === s ? '#a78bfa' : 'var(--text-secondary)',
                border: `1px solid ${status === s ? 'rgba(124,58,237,0.35)' : 'var(--border)'}`,
                transition: 'all 0.2s',
              }}
            >{s}</button>
          ))}
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '0.78rem', color: 'var(--text-muted)' }}>
          <Calendar size={13} /> May 2026
        </div>
      </div>

      {/* Table */}
      <div className="card animate-fade-in-up" style={{ padding: 0, overflow: 'hidden' }}>
        <div style={{ padding: '16px 20px', borderBottom: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div style={{ fontFamily: 'Space Grotesk, sans-serif', fontWeight: 700, fontSize: '0.95rem' }}>
            <FileText size={15} style={{ display: 'inline', marginRight: '6px', color: '#a78bfa', verticalAlign: 'middle' }} />
            Salary Slips
          </div>
          <span className="badge badge-info">{filtered.length} records</span>
        </div>
        <div style={{ overflowX: 'auto' }}>
          <table className="data-table">
            <thead>
              <tr>
                <th>Employee</th>
                <th>ID</th>
                <th style={{ textAlign: 'right' }}>Base</th>
                <th style={{ textAlign: 'right' }}>HRA</th>
                <th style={{ textAlign: 'right' }}>Allow.</th>
                <th style={{ textAlign: 'right' }}>Deduct.</th>
                <th style={{ textAlign: 'right' }}>Net Salary</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((r, i) => (
                <tr key={i}>
                  <td style={{ whiteSpace: 'nowrap' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                      <div style={{
                        width: '28px', height: '28px', borderRadius: '7px', flexShrink: 0,
                        background: 'linear-gradient(135deg, #7c3aed, #4f46e5)',
                        display: 'flex', alignItems: 'center', justifyContent: 'center',
                        fontSize: '0.65rem', fontWeight: 800, color: '#fff',
                      }}>
                        {r.employee?.name.split(' ').map(n => n[0]).join('').slice(0,2)}
                      </div>
                      <span style={{ fontWeight: 600, fontSize: '0.82rem' }}>{r.employee?.name}</span>
                    </div>
                  </td>
                  <td><span className="badge badge-info" style={{ fontSize: '0.62rem' }}>{r.employeeId}</span></td>
                  <td style={{ textAlign: 'right', fontSize: '0.8rem' }}>₹{(r.baseSalary/1000).toFixed(0)}K</td>
                  <td style={{ textAlign: 'right', fontSize: '0.8rem', color: '#34d399' }}>₹{(r.hra/1000).toFixed(0)}K</td>
                  <td style={{ textAlign: 'right', fontSize: '0.8rem', color: '#22d3ee' }}>₹{(r.allowances/1000).toFixed(0)}K</td>
                  <td style={{ textAlign: 'right', fontSize: '0.8rem', color: '#f87171' }}>-₹{(r.deductions/1000).toFixed(0)}K</td>
                  <td style={{ textAlign: 'right', fontFamily: 'Space Grotesk, sans-serif', fontWeight: 700, color: '#a78bfa', whiteSpace: 'nowrap' }}>
                    ₹{r.net.toLocaleString('en-IN')}
                  </td>
                  <td><span className={`badge ${statusBadgeClass[r.status]}`}>{r.status}</span></td>
                  <td>
                    <div style={{ display: 'flex', gap: '5px' }}>
                      <button
                        title="View slip"
                        onClick={() => setSelected(r)}
                        style={{
                          width: '28px', height: '28px', borderRadius: '6px', border: '1px solid var(--border-bright)',
                          background: 'var(--bg-secondary)', cursor: 'pointer', color: '#a78bfa',
                          display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.2s',
                        }}
                        onMouseEnter={e => { e.currentTarget.style.borderColor = '#7c3aed'; e.currentTarget.style.background = 'rgba(124,58,237,0.15)' }}
                        onMouseLeave={e => { e.currentTarget.style.borderColor = 'var(--border-bright)'; e.currentTarget.style.background = 'var(--bg-secondary)' }}
                      ><Eye size={12} /></button>
                      <button
                        title="Download PDF"
                        onClick={() => toast('PDF download — connect backend!')}
                        style={{
                          width: '28px', height: '28px', borderRadius: '6px', border: '1px solid var(--border-bright)',
                          background: 'var(--bg-secondary)', cursor: 'pointer', color: '#34d399',
                          display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.2s',
                        }}
                        onMouseEnter={e => { e.currentTarget.style.borderColor = '#10b981'; e.currentTarget.style.background = 'rgba(16,185,129,0.15)' }}
                        onMouseLeave={e => { e.currentTarget.style.borderColor = 'var(--border-bright)'; e.currentTarget.style.background = 'var(--bg-secondary)' }}
                      ><Download size={12} /></button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
